### ISSUE TITLE
[FEATURE]: Add useful packages for NTFS, printing and  theming

### ISSUE THREAD

**Issue by janvhs** [crystal-linux/iso#34]
### Is your feature request related to a problem? Please describe.

I encountered some hurdles trying to use the dark theme on "old" GTK apps like VS Code, the printer and an external USB-drive.
Furthermore, just for completeness, `bluetooth.service` is not enabled by default.

### Describe the solution you'd like

I would like the iso to include the following packages:

- ntfs-3g
	- A ntfs file system driver
- gnome-themes-extra
	- Themes for old gtk apps
- cups
	- A printing service. Idk if it was installed already.
	- With the service enabled

### Describe alternatives you've considered

There are no real alternatives to new users.

### Additional context

I would contribute this myself, but I don't know where to put these packages :thinking: 

Thank you all for this distro :heart: :rainbow:

**Comment by Antiz96** [comment]
Hello @bode-fun,

Thanks for the suggestion!
As far as `ntfs-3g` and `cups` are concerned, their inclusion has already been approved in a recent RFC actually! This is being worked on, so hopefully they'll make it to the future ISOs :smile:
We've also decided to install `bluez` for the bluetooth support out of the box.

About `gnome-themes-extra`, it has to be discussed I think. This package is not part of the `gnome` group package (not even the `gnome-extra` group package actually), and we want to ship our desktop environments/standalone window managers as vanilla as possible. 
The need of the `gnome-themes-extra` package seems to be centered over users particular cases/needs more than a "nice to have" for everyone, in my opinion.
I think it should be debated on our side before deciding if we include it by default or not.

Anyway thanks for your suggestions once again!

**Comment by Antiz96** [comment]
@bode-fun Sorry for letting this Feature request died on GitHub side. 
Since we migrated to GitLab, *mostly* everything have been moved over to it but we're still working on the GitHub side.

In case you haven't seen it, your feature request has been added to the [related RFC](https://git.getcryst.al/crystal/info/-/issues/8) which has, since then, [been merged](https://git.getcryst.al/crystal/software/jade/-/merge_requests/63)!

The new ISO will contain support out of the box for printers and NTFS ;)
